geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
shareButtons:
  size: small
  networks:
    - twitter
    - reddit
    - linkedin